[package]
name = "drs-project-access"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
drs-model = { path = "../drs-model" }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[features]
default = []
dev = ["drs-model/dev"]

[lints]
workspace = true
