[package]
name = "cli"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license-file.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
assets = { workspace = true }
clap = { version = "4.5.41", features = ["derive"] }
clap-verbosity-flag = { version = "3.0.3", default-features = false, features = ["tracing"] }
anyhow = { workspace = true }
dialoguer = { version = "0.11.0", default-features = false, features = [] }
indicatif = { version = "0.18.0", features = [] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[lints]
workspace = true

[features]
default = []
dev = [
    "assets/dev"
]
