[package]
name = "cli"
edition = "2024"
version.workspace = true
license-file.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
