[package]
name = "drs-model"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_math = { workspace = true }
bevy_reflect = { workspace = true }
drs-history = { path = "../drs-history" }
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[features]
default = []
dev = ["drs-history/dev"]

[lints]
workspace = true
