use bevy::log::{DEFAULT_FILTER, LogPlugin};
use bevy::utils::default;
use tracing_appender::rolling::daily;
use tracing_subscriber::Layer;
use tracing_subscriber::fmt::layer;

/// Generates a [`LogPlugin`] for Bevy.
///
/// The plugin generated by this method is automatically configured for log level and file output.
#[must_use]
pub fn log_plugin() -> LogPlugin {
    LogPlugin {
        filter: format!("{DEFAULT_FILTER},core=trace,editor=trace,headless=trace,ui=trace"),
        custom_layer: |_app| {
            let writer = daily("logs", "dungeonrs");

            Some(Box::new(vec![
                layer().with_file(true).boxed(),
                layer()
                    .with_file(false)
                    .with_thread_names(true)
                    .with_thread_ids(true)
                    .with_level(true)
                    .json()
                    .with_writer(writer)
                    .boxed(),
            ]))
        },
        ..default()
    }
}
