name: "🐛 Bug report"
description: Report something that isn't working as it should or is outright broken
title: "[BUG]: "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              **Before You Start...**

              This form is only for submitting bug reports. If you have a usage question
              or are unsure if this is really a bug, make sure to:

              - Read the [documentation](https://github.com/dungeon-rs/dungeon-rs/blob/master/README.md)
              - Check [existing issues](https://github.com/dungeon-rs/dungeon-rs/issues) for similar problems
              - Ask on [GitHub Discussions](https://github.com/dungeon-rs/dungeon-rs/discussions)

              Also try to search for your issue - it may have already been answered or even fixed in the development branch.
              However, if you find that an old, closed issue still persists in the latest version,
              you should open a new issue using the form below instead of commenting on the old issue.

    - type: input
      id: dungeonrs-version
      attributes:
          label: DungeonRS Version
          description: |
              Please provide the version of DungeonRS you are using. You can find this in the application's About dialog.
          placeholder: "e.g., 0.1.0"
      validations:
          required: true

    - type: dropdown
      id: operating-system
      attributes:
          label: Operating System
          description: Which operating system are you using?
          options:
              - Windows 10
              - Windows 11
              - macOS (Intel)
              - macOS (Apple Silicon)
              - Linux (Ubuntu/Debian)
              - Linux (Fedora/RHEL)
              - Linux (Arch)
              - Linux (Other)
              - Other (Specify in comments)
      validations:
          required: true

    - type: dropdown
      id: custom-content
      attributes:
          label: Are you using custom scripts or shaders?
          description: Custom scripts or shaders might affect DungeonRS behaviour
          options:
              - "No custom content"
              - "Using custom scripts only"
              - "Using custom shaders only"
              - "Using both custom scripts and shaders"
              - "Not sure"
      validations:
          required: true

    - type: textarea
      id: steps-to-reproduce
      attributes:
          label: Steps to reproduce
          description: |
              Please provide clear, step-by-step instructions to reproduce the bug.
              Include specific actions like "Create new project", "Add layer", "Import asset", etc.
          placeholder: |
              1. Open DungeonRS
              2. Create a new project
              3. Click on...
              4. See error
      validations:
          required: true

    - type: textarea
      id: expected-behaviour
      attributes:
          label: Expected behaviour
          description: |
              What did you expect to happen? Describe the intended behaviour clearly.
      validations:
          required: true

    - type: textarea
      id: actual-behaviour
      attributes:
          label: Actual behaviour
          description: |
              What actually happened? Describe what went wrong, including any error messages,
              crashes, or unexpected behaviour.
      validations:
          required: true

    - type: textarea
      id: crash-report
      attributes:
          label: Crash report (if applicable)
          description: |
              If DungeonRS crashed, please include the contents of the `crash_report.txt` file
              that should have been generated (the crash popup tells you where). You can drag and drop
              the file here or copy and paste its contents.
          render: text
          placeholder: Paste crash report contents here...

    - type: textarea
      id: project-details
      attributes:
          label: Project details (if applicable)
          description: |
              If this bug occurs with a specific project, please provide details:
              - Project complexity (number of levels, layers, assets)
              - Asset pack information
              - Project file size
              - Any custom settings or configurations
          placeholder: |
              - Project has 3 levels, 5-8 layers each
              - Using Forgotten Adventures asset pack
              - Project file size: ~15MB
              - Custom brush settings enabled

    - type: textarea
      id: log-output
      attributes:
          label: Log output (if available)
          description: |
              If you have access to log files (check the `logs/` directory in your DungeonRS folder),
              please include any relevant error messages or warnings. You can drag and drop
              log files here or copy and paste the contents.

              <details>
              <summary>Click to expand log content</summary>

              ```
              Paste your log content here
              ```

              </details>
          placeholder: |
              <details>
              <summary>Log files</summary>

              ```
              Paste relevant log entries here...
              ```

              </details>

    - type: textarea
      id: system-info
      attributes:
          label: System Information
          description: |
              Please provide information about your system that might be relevant.

              **Need help finding this information?**
              - **Windows**: Press `Win + R`, type `dxdiag`, press Enter. Look for "System" and "Display" tabs
              - **macOS**: Apple menu → About This Mac. For GPU info: System Information → Graphics/Displays
              - **Linux**: Run `lscpu`, `lspci | grep VGA`, and `free -h` in terminal

              **What we need:**
              - GPU model and driver version
              - Available RAM
              - Storage type (SSD/HDD)
              - Display configuration (resolution, scaling, multiple monitors)
          render: text
          placeholder: |
              GPU: NVIDIA RTX 3070, Driver 531.61
              RAM: 16GB
              Storage: NVMe SSD
              Display: 2560x1440 @ 144Hz, 125% scaling

    - type: textarea
      id: additional-context
      attributes:
          label: Additional context
          description: |
              Add any other context about the problem here. This might include:
              - Screenshots or recordings (drag and drop files here)
              - Workarounds you've discovered
              - Similar issues in other applications
              - When the problem started occurring
          placeholder: Any additional information that might help us understand and fix the issue...

    - type: markdown
      attributes:
          value: |
              ---

              **Important Notes:**

              - **Complete information required**: Issues that are incomplete or missing required information will be automatically closed. Please fill out all required fields thoroughly.

              - **Additional information**: Maintainers may request additional information, logs, or steps to reproduce the issue. Please respond promptly to help us resolve your issue quickly.

              - **Attachments**: You can drag and drop files (screenshots, crash reports, log files, project files) directly into any text area above.

              - **Response time**: We'll do our best to respond quickly, but please be patient as this is a volunteer-maintained project.

              - **Duplicates**: Before submitting, please search existing issues to avoid duplicates. We may close duplicate reports in favour of the original issue.

              Thank you for helping improve DungeonRS! 🗺️
