blank_issues_enabled: false
contact_links:
    - name: Questions & Discussions
      url: https://github.com/dungeon-rs/dungeon-rs/discussions
      about: Use GitHub discussions for message-board style questions, discussions and feature requests
    - name: Buy me a coffee
      url: https://www.buymeacoffee.com/dealloc
      about: If you want to support the development, check out buymeacoffee
