[package]
name = "drs-catalog-engine"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
caseless = { workspace = true }
drs-model = { path = "../drs-model" }
unicode-normalization = { workspace = true }

[features]
default = []
dev = ["drs-model/dev"]

[lints]
workspace = true
