[package]
name = "drs-editor"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bevy = { workspace = true }
bevy_egui = { workspace = true }
drs-history = { path = "../drs-history" }
drs-model = { path = "../drs-model" }
egui = { workspace = true }
egui_dock = { workspace = true }
rfd = { workspace = true }

[features]
default = []
dev = ["drs-history/dev", "drs-model/dev"]

[lints]
workspace = true
