[package]
name = "drs-authoring-manager"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[features]
default = []
dev = []

[lints]
workspace = true
