[package]
name = "drs-authoring-manager"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_math = { workspace = true }
drs-history = { path = "../drs-history" }
drs-library-access = { path = "../drs-library-access" }
drs-model = { path = "../drs-model" }
log = { workspace = true }
thiserror = { workspace = true }
unicode-normalization = { workspace = true }

[features]
default = []
dev = ["drs-history/dev", "drs-library-access/dev", "drs-model/dev"]

[lints]
workspace = true
