[package]
name = "editor"
edition.workspace = true
repository.workspace = true
version.workspace = true
readme.workspace = true
authors.workspace = true
license.workspace = true
description = "The editor binary, this starts the UI and is intended to be the user facing binary"

[dependencies]
ui = { path = "../ui", default-features = false }
core = { path = "../core", default-features = false }
bevy = { workspace = true, features = [
  "multi_threaded",
  "bevy_window",
  "bevy_winit",
  "bevy_log",
  # image formats
  "png",
  "jpeg",
  "webp"
] }

[build-dependencies]
image = { version = "0.25.6", default-features = false, features = ["png", "ico"] }
winresource = "0.1.20"

[features]
default = ["dev", "core/json"]
dev = [
  "bevy/trace",
  "bevy/track_location",
  "bevy/dynamic_linking",
  "bevy/bevy_dev_tools",
  "bevy/bevy_debug_stepping",
  "bevy/file_watcher",
  "core/dev",
  "ui/dev"
]

windows = [
  "core/windows",
  "ui/windows"
]
linux = [
  "bevy/x11",
  "bevy/wayland",
  "bevy/accesskit_unix",
  "core/linux",
  "ui/linux"
]
macos = [
  "bevy/accesskit_unix",
  "core/macos",
  "ui/macos"
]
