[package]
name = "drs-project-manager"
edition.workspace = true
version.workspace = true
license.workspace = true
readme.workspace = true
rust-version.workspace = true
publish.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
bevy_app = { workspace = true }
bevy_ecs = { workspace = true }
bevy_math = { workspace = true }
drs-catalog-engine = { path = "../drs-catalog-engine" }
drs-history = { path = "../drs-history" }
drs-model = { path = "../drs-model" }
drs-output-access = { path = "../drs-output-access" }
drs-paint-engine = { path = "../drs-paint-engine" }
drs-project-access = { path = "../drs-project-access" }
drs-render-engine = { path = "../drs-render-engine" }
thiserror = { workspace = true }

[features]
default = []
dev = [
  "drs-catalog-engine/dev",
  "drs-history/dev",
  "drs-model/dev",
  "drs-output-access/dev",
  "drs-paint-engine/dev",
  "drs-project-access/dev",
  "drs-render-engine/dev",
]

[lints]
workspace = true
