name: Update documentation

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'docs/**'
      - '*.md'
      - 'CONTRIBUTING'
      - 'SECURITY.md'
      - 'LICENSE'
  push:
    branches: [ master ]

jobs:
  docs:
    runs-on: ubuntu-latest
    name: Generate documentation
    permissions:
      contents: write
      id-token: write
      pages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - uses: taiki-e/install-action@v2
        with:
          tool: mdbook

      - uses: Swatinem/rust-cache@v2

      - name: Build API documentation
        run: cargo doc --profile=fast --locked --workspace --all-features --document-private-items --no-deps

      - name: Build documentation
        working-directory: docs
        run: mdbook build

      - name: Copy API documentation to docs folder
        run: cp -r target/doc/* docs/book/api

      - name: Upload static files as artefact
        if: github.event_name == 'push'
        id: deployment-artifact
        uses: actions/upload-pages-artifact@v4 # or specific "vX.X.X" version tag for this action
        with:
          path: docs/book

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        id: deployment-pages
        uses: actions/deploy-pages@v4
